/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;


import java.util.NoSuchElementException;
import java.util.Scanner;

public class App {
    private static String getGreeting() {
        return "Hello and welcome to robotSim!";
    }

    private static String roomSizePrompt() {
        return "roomsize:";
    }

    private static String robotStartPrompt() {
        return "robotstart:";
    }

    private static String movementPrompt() {
        return "enter movements:";
    }

    public static void main(String[] args) {
        System.out.println(getGreeting());
        Room room = createRoom();
        Robot robot = createRobot(room);
        controlRobot(robot);
        System.out.println(robot.toString());
    }

    private static Room createRoom() {
        Scanner scanner = new Scanner(System.in);
        String input = "";
        Room room = null;
        boolean roomCreated = false;
        while(!roomCreated) {
            try {
                System.out.println(roomSizePrompt());
                input = scanner.nextLine();
                System.out.println("you entered: " + input);
            } catch(NoSuchElementException e) {
                System.out.println(e.getMessage());
            }
            try {
                room = new Room(input);
                roomCreated = true;
            } catch(IllegalArgumentException e) {
                System.out.println(e.getMessage());
            }
        }
        return room;
    }

    private static Robot createRobot(Room room) {
        Scanner scanner = new Scanner(System.in);
        String input = "";
        Robot robot = null;
        System.out.println(robotStartPrompt());
        boolean robotCreationSuccessful = false;
        while(!robotCreationSuccessful) {
            try {
                input = scanner.nextLine();
                System.out.println("you entered: " + input);
            } catch(NoSuchElementException e) {
                System.out.println(e.getMessage());
            }
            try{
                robot = new Robot(input, room);
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
        return robot;
    }

    private static void controlRobot(Robot robot) {
        Scanner scanner = new Scanner(System.in);
        String input = "";
        boolean successfullyMoved = false;
        while(!successfullyMoved) {
            System.out.println(movementPrompt());
            try {
                input = scanner.nextLine();
                System.out.println("you entered: " + input);
            } catch(NoSuchElementException e) {
                System.out.println(e.getMessage());
            }
            try {
                robot.executeStringOfCommands(input);
                successfullyMoved = true;
            } catch (Exception e) {
                if(e instanceof IndexOutOfBoundsException) {
                    System.out.println(e.getMessage());
                    break;
                }
                System.out.println(e.getMessage());
            }
        }
    }
}
